### ISSUE TITLE
Toolbar gets hidden in UpdateToolbar() if ShowCameraButton is false and you have made a selection

### ISSUE THREAD

**Issue by Cybrosys** [roycornelissen/GMImagePicker.Xamarin#1]
GMImagePickerController.cs line 387:
`var toolbarHidden = _selectedAssets.Any () && !ShowCameraButton;`
Should be:
`var toolbarHidden = !_selectedAssets.Any () && !ShowCameraButton;`

As soon as a selection is made, the toolbar gets hidden.

**Comment by roycornelissen** [comment]
Good catch! You're totally right. I didn't notice because I have the camera button turned on. I'm about to push a fix, including some fixes for issue #2.

Thanks!

**Comment by roycornelissen** [comment]
0.0.8 is now out on Nuget, including this fix.
