### ISSUE TITLE
Inaccurate Asset Counts for Collections

### ISSUE THREAD

**Issue by alexrfan03** [roycornelissen/GMImagePicker.Xamarin#18]
When showing the collections in the album view, the totals only show a maximum of 3.

Collections only show 3 images max.
![image](https://user-images.githubusercontent.com/637261/33625920-c1dd00d4-d9be-11e7-9c68-c5f3b807bcbd.png)

How many images are actually in the collection.
![image](https://user-images.githubusercontent.com/637261/33625939-cee3cf74-d9be-11e7-9919-4bfafe6f7ffe.png)

I believe it's because you are calling PHAssets.FetchKeyAssets instead of PHAssets.FetchAssets like you are doing in the "Camera Roll" call, but I don't know what the ramifications of changing that call.

**Comment by alexrfan03** [comment]
I forked your repo and made the changes to switch from FetchKeyAssets to FetchAssets, and I am getting the correct results now. Is there a reason you used the FetchKeyAssets compared to FetchAssets?

**Comment by roycornelissen** [comment]
@alexrfan03 Thanks for catching this bug. It's not intentional to do FetchKeyAssets instead of FetchAsset, so as far as I'm concerned it's a bug. I think probably it's because the thumbnail of the collection is showing only 3 pictures, but then the item count is indeed incorrect. I'll have a quick look if this fix is sufficient.

**Comment by roycornelissen** [comment]
V2.0.1 has been submitted to Nuget with the fix in place. Thanks @alexrfan03 !

**Comment by alexrfan03** [comment]
Awesome! I wasn't sure if it was some memory problem. Thank you for the update.

**Comment by roycornelissen** [comment]
Not really a memory issue. The PHAsset API is highly optimized, it doesn’t fetch the actual images, only some metadata and a handle to the image file. Tested it on my iPhone 7 and my camera roll with 2300 photos loads in the blink of an eye 😊
