### ISSUE TITLE
Customize the imagepicker view

### ISSUE THREAD

**Issue by ghatighorias** [roycornelissen/GMImagePicker.Xamarin#19]
Hi I want to customize the picker view but i can't find how,

basically i want to completely change the navigation bar and add one button at the bottom. is this possible with this component ?

thanks a lot

**Comment by roycornelissen** [comment]
Hi @ghatighorias, sorry for the late reply... I have merged @pragmatrix's PR, which is now part of version 2.1.0 on Nuget. This allows you to add buttons to the bottom bar (see the README.md and the demp app for a sample).

As for the navigation bar, I'm not sure what kind of changes you want to make... can you elaborate? Or did you find a way already to do so?
