### ISSUE TITLE
Can't install NuGet package

### ISSUE THREAD

**Issue by gianisimone** [roycornelissen/GMImagePicker.Xamarin#26]
I am trying to install your library through NuGet in my Xamarin Forms project. I get this error during the installation process:
`Package GMImagePicker.Xamarin 2.1.0 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package GMImagePicker.Xamarin 2.1.0 supports: xamarinios10 (Xamarin.iOS,Version=v1.0)`

What should I do to install your package?

**Comment by roycornelissen** [comment]
Hi, this is a pure iOS native library so it can’t be added to a shared library. If you want to use it, you should add it to the iOS project and used from there. You could probably create an abstraction over it to use it from Forms but remember that the images returned are of type PHAsset, which is iOS specific.

**Comment by gianisimone** [comment]
Thank you for your quick answer
