### ISSUE TITLE
Previous Image Selection Exists! 

### ISSUE THREAD

**Issue by SatyaRamprasad** [roycornelissen/GMImagePicker.Xamarin#27]
![image](https://user-images.githubusercontent.com/17923089/39921372-408c39be-5538-11e8-85ef-ef9c8f630c66.png)

Previous Image Selections Exists,Even for new selection or instance

**Comment by roycornelissen** [comment]
The only way I can explain this is that the selected assets have been added to the Assets collection of the `GMImagePickerController`'s `SelectedAssets` collection before being showed. The sample app also does this, see line 81 in `ViewController.cs`:

https://github.com/roycornelissen/GMImagePicker.Xamarin/blob/4cb371a58b40c058cbfc0ee5d828b595d32e4d63/src/GMPhotoPicker.Xamarin/ViewController.cs#L81

**Comment by nguyenthanhliemfc** [comment]
> The only way I can explain this is that the selected assets have been added to the Assets collection of the `GMImagePickerController`'s `SelectedAssets` collection before being showed. The sample app also does this, see line 81 in `ViewController.cs`:
> 
> https://github.com/roycornelissen/GMImagePicker.Xamarin/blob/4cb371a58b40c058cbfc0ee5d828b595d32e4d63/src/GMPhotoPicker.Xamarin/ViewController.cs#L81

How to clear selected image of the last time selection? Thank!
