### ISSUE TITLE
Review and update translations for no - Norwegian

### ISSUE THREAD

**Issue by roycornelissen** [roycornelissen/GMImagePicker.Xamarin#52]
Up for grabs: please review and update/complete the translations in the no.lproj/GMImagePicker.strings file for the language no (Norwegian). Use the original labels in Base.lproj as a starting point.

Contributions are highly appreciated!

**Comment by jasonctoms** [comment]
I just made a PR for this issue :)

**Comment by roycornelissen** [comment]
You are awesome! I hope to find some time this week to incorporate and release all the PR’s and bugfixes.

Thanks!!
