### ISSUE TITLE
Translations not working

### ISSUE THREAD

**Issue by mleatherb** [roycornelissen/GMImagePicker.Xamarin#54]
When a user launches the GMImagePicker and tries to select Albums and they did not give the app permission to photos they are greeted with a *NO TRANSLATION* error message. 

It appears to be an issue with the way we have configured our app. I added the localizations to the plist file, but that doesn't fix it. Is there any specific configuration I need for the translations to work?

**Comment by Jose7777** [comment]
I also cannot make it work; how can I configure translations?

Thank you in advance

**Comment by roycornelissen** [comment]
@mleatherb the translations chosen depend on the locale settings of the device, in the device settings. There's currently no API built into this component to manually select/override the language as a developer. Which language did this user configure? Most probably it is a language where there's indeed no translation available; although it should actually default to English normally.

**Comment by MarcelWinkelEBF** [comment]
> @mleatherb the translations chosen depend on the locale settings of the device, in the device settings. There's currently no API built into this component to manually select/override the language as a developer. Which language did this user configure? Most probably it is a language where there's indeed no translation available; although it should actually default to English normally.

Hi, translations for me also not working, but just for the title and message. If I trigger the permissions alert it shows translations for the Cancel and Settings button but not for the other strings. Devices are in English and German, so the English strings should definitely work right?

**Comment by MarcelWinkelEBF** [comment]
@roycornelissen with the latest package in simulator it looks like it's working. But not after deploying on a phone

**Comment by maksym-husiev** [comment]
Hi! Translation not working. I can't say for sure, but maybe it's related to missed info.plist config sections?
Something like this (I'm using this in my app to get it translated):
`	<key>CFBundleLocalizations</key>
	<array>
		<string>ru</string>
	</array>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>`

**Comment by roycornelissen** [comment]
@maksym-husiev I think that is indeed the case. I added these keys to the `info.plist` of the sample application for reference. Indeed I am getting the translations if I switch to Dutch. I haven't tested other ones, but I think it is a matter of adding the proper keys to `info.plist`.

Thanks!

**Comment by maksym-husiev** [comment]
@roycornelissen Ok, thx! Will try get picker translated with next version (2.5, because of issue related to iOS 14)

**Comment by ASkiff-F360** [comment]
I know this issue has been closed for a while, but I still get the *NO TRANSLATION* popup even after adding the CFBundleLocalizations to my Info.pList. Is there something else I'm missing?
