### ISSUE TITLE
GMGridViewCell ExportAttribute selector is wrong, breaks build

### ISSUE THREAD

**Issue by Cybrosys** [roycornelissen/GMImagePicker.Xamarin#6]
[Export("initWithFrame:frame")]
public GMGridViewCell (CGRect frame) : base(frame)

Should be
[Export("initWithFrame:")]
public GMGridViewCell (CGRect frame) : base(frame)

**Comment by roycornelissen** [comment]
I merged your PR and published 0.0.9 of the package to Nuget just now. Should be updated within a couple of minutes. Thanks for noticing and providing a fix!
