### ISSUE TITLE
Does Xamarin forms IOS supports this package?

### ISSUE THREAD

**Issue by SatyaRamprasad** [roycornelissen/GMImagePicker.Xamarin#61]
Before upgrading from PCL to .NetStandard, it worked on xamarin forms ios.
But now it is not working and here is my code:

public async Task OpenGallery()
        {
            var picker = new GMImagePickerController
            {
                Title = "Custom Title",
                CustomDoneButtonTitle = "Finished",
                CustomCancelButtonTitle = "Nope",
                CustomNavigationBarPrompt = "Take a new photo or select an existing one!",
                ColsInPortrait = 3,
                ColsInLandscape = 5,
                MinimumInteritemSpacing = 2.0f,
                DisplaySelectionInfoToolbar = true,
                AllowsMultipleSelection = true,
                ShowCameraButton = true,
                AutoSelectCameraImages = true,
                AllowsEditingCameraImages = true,
                ModalPresentationStyle = UIModalPresentationStyle.Popover,
                MediaTypes = new[] { PHAssetMediaType.Image },
            };

            // You can limit which galleries are available to browse through
            picker.CustomSmartCollections = new[] {
                PHAssetCollectionSubtype.SmartAlbumUserLibrary,
                PHAssetCollectionSubtype.AlbumRegular
            };

            if (_preselectedAssets != null)
            {
                foreach (var asset in _preselectedAssets)
                {
                    picker.SelectedAssets.Add(asset);
                }
            }

            // Event handling
            picker.FinishedPickingAssets += Picker_FinishedPickingAssets;
            picker.Canceled += Picker_Canceled;

            // Other events to implement in order to influence selection behavior:
            // Set EventArgs::Cancel flag to true in order to prevent the action from happening
            picker.ShouldDeselectAsset += (s, e) => { /* allow deselection of (mandatory) assets */ };
            picker.ShouldEnableAsset += (s, e) => { /* determine if a specific asset should be enabled */ };
            picker.ShouldHighlightAsset += (s, e) => { /* determine if a specific asset should be highlighted */ };
            picker.ShouldShowAsset += (s, e) => { /* determine if a specific asset should be displayed */ };
            picker.ShouldSelectAsset += (s, e) => { /* determine if a specific asset can be selected */ };

            picker.AssetSelected += (s, e) => { /* keep track of individual asset selection */ };
            picker.AssetDeselected += (s, e) => { /* keep track of individual asset de-selection */ };

            // GMImagePicker can be treated as a PopOver as well:
            var popPC = picker.PopoverPresentationController;
            popPC.PermittedArrowDirections = UIPopoverArrowDirection.Any;
            await PresentViewControllerAsync(picker, true);
        }

**Comment by SatyaRamprasad** [comment]
@roycornelissen  Any help would be very useful?
Thanks in advance.

**Comment by roycornelissen** [comment]
Hi @SatyaRamprasad, the library should be usable from a Xamarin.Forms application, although it's iOS specific code. Are you using the library from a shared code base? That may be the problem, because this is specifically a Xamarin iOS library. So I think you will have a hard time consuming the library from cross platform code, since it's not made to be used in a cross platform manner. You probably have to wrap it in an abstraction which is injected through dependency injection into your shared code.

Can you be more specific about the error message you are getting?

**Comment by SatyaRamprasad** [comment]
@roycornelissen Thanks for the quick reply..
Iam not getting any error, gallery screen is not popping up after presentviewcontroller.
Previously it worked for me in pcl after upgrading it to .net standard, it is not working.

**Comment by roycornelissen** [comment]
Can you share info about the project structure in your solution? Personally I haven't tested the library with netstandard yet, I was assuming it would always be referenced from an iOS csproj.

**Comment by amirvenus** [comment]
Is there a working example for using it in XF via DependecyService?

**Comment by roycornelissen** [comment]
@amirvenus not really but you could have a look at how https://github.com/jamesmontemagno/MediaPlugin is implemented.

Coincidentally, @jamesmontemagno just opened #17, asking to consider integrating this component into Xam.Plugin.Media. So possibly soon you will have it out of the box 😉
