### ISSUE TITLE
How to set Back button Title

### ISSUE THREAD

**Issue by Firice** [roycornelissen/GMImagePicker.Xamarin#62]
Hi,

I want to set back button title is null. But GMImagePickerController Option can't found it. Can you have this option?

**Comment by roycornelissen** [comment]
Hi, thanks for submitting this request, and sorry for my slow response 🙈 

I have added two new options to the picker, will be released in 2.5.0.

You can now set `CustomBackButtonTitle` to override the text of the back button, and I have also exposed `BackButtonDisplayMode` which can be overridden. It is available in iOS >= 14.0. You can set it to `UINavigationItemBackButtonDisplayMode.Minimal` to clear the title. For backwards compatibility, it will set the title to `string.Empty` in iOS <= 14.0 if it is `UINavigationItemBackButtonDisplayMode.Minimal`.

Let me know if this works for you.
