### ISSUE TITLE
Checkmark image is not visible on selected items

### ISSUE THREAD

**Issue by sergbuk** [roycornelissen/GMImagePicker.Xamarin#65]
Checkmark images are not visible on selected items. I just run the GMPhotoPicker.Xamarin project without any changes. Please see the screenshot for details.

![Sample](https://user-images.githubusercontent.com/50649782/67927314-92629800-fbb8-11e9-860b-8c5b1a692efa.png)

**Comment by sergbuk** [comment]
I found that following change (adding _selectedButton to _coverView) fixes it.

`//GMGridViewCell.cs`
`public void Initialize () `
`{`
`...`
`_selectedButton.SetImage (null, UIControlState.Normal);`
`_selectedButton.SetImage (UIImage.FromFile ("GMSelected"), UIControlState.Selected);`
` _coverView.AddSubview(_selectedButton);`
`...`

**Comment by roycornelissen** [comment]
Hi, cool, would you like to make a PR for it?

**Comment by sergbuk** [comment]
Hi Roy, could you please check the PR?

**Comment by divyesh008** [comment]
Facing same issue, have you got any solution?

**Comment by divyesh008** [comment]
> I found that following change (adding _selectedButton to _coverView) fixes this problem.
> 
> `//GMGridViewCell.cs`
> `public void Initialize () `
> `{`
> `...`
> `_selectedButton.SetImage (null, UIControlState.Normal);`
> `_selectedButton.SetImage (UIImage.FromFile ("GMSelected"), UIControlState.Selected);`
> ` _coverView.AddSubview(_selectedButton);`
> `...`

exactly where this change needs to be add ?

**Comment by sergbuk** [comment]
@divyesh008 
add following line:
`_coverView.AddSubview(_selectedButton);`
after this one:
`_selectedButton.SetImage (UIImage.FromFile ("GMSelected"), UIControlState.Selected);`

**Comment by roycornelissen** [comment]
The PR for this has been merged. Closing the issue.

**Comment by martin-steglich** [comment]
Hi, I know this issue is closed since Sep 23 but I'm facing with it, image selected checkmark isn't visible. 

I'm creating the picker this way: 
` 
var picker = new GMImagePickerController
            {
                Title = "Select Photo",
                CustomDoneButtonTitle = "Finished",
                CustomCancelButtonTitle = "Cancel",
                ColsInPortrait = 4,
                ColsInLandscape = 7,
               
                DisplaySelectionInfoToolbar = true,
                AllowsMultipleSelection = true,
                ShowCameraButton = true,
                AutoSelectCameraImages = true,
                
                ModalPresentationStyle = UIModalPresentationStyle.FullScreen,
                MediaTypes = new[] { PHAssetMediaType.Image },
               `
@roycornelissen @sergbuk, Can you help me?

Thank you!

**Comment by PredatH0r** [comment]
This is still an issue.
I'm using NuGet "GMImagePicker.Xamarin" version 2.5.1 in a VS2019 (16.11.3) Xamarin.iOS (14.20.0.25) project running on an iPhone 8 iOS 13.7 Simulator on a Mac Mini M1 with Xcode 12.5.

Selected images receive a blue-ish overlay, but no check box.

FWIW: I can't use any newer Xcode (e.g. 13) or simulator (e.g. iOS 14/15) because of various incompatibilities with Xamarin hot reload and broken ImagePicker running in a simulator on M1 silicon)
