### ISSUE TITLE
Font issue on iOS13

### ISSUE THREAD

**Issue by nick-sturrock** [roycornelissen/GMImagePicker.Xamarin#70]
I've implemented the picker in iOS13, which works well, however it doesn't pick up the system typeface and gives me Times New Roman as a substitute. I tried using the PickerFontName option to change the typeface but this also fails if I use a system font style. Trace shows as follows:

`CoreText note: Client requested name ".SFUIDisplay", it will get TimesNewRomanPSMT rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[UIFont systemFontOfSize:].`

Should note that this works correctly when using non-system fonts so for the time being I have opted to use 'Helvetica' rather than the SFFont family.

**Comment by roycornelissen** [comment]
Hi @nick-sturrock, thanks for reporting. In iOS 13 you cannot refer to a system font by name anymore. I borrowed some code from Xamarin Forms, where they solved the same issue. Should arrive in the updated Nuget package soon.
