### ISSUE TITLE
iOS 14 NullreferenceException crash

### ISSUE THREAD

**Issue by MarcelWinkelEBF** [roycornelissen/GMImagePicker.Xamarin#77]
@roycornelissen 

Hi Roy, thanks for your work with this NuGet package! :)

In order to more Tests with the current iOS 14 beta Versions I came across one crash when using iOS 14 as deploy target.
Inside the GMAlbumsViewController there is a NullreferenceException on the header.BackgroundView.BackgroundColor. Inside the WillDisplayHeaderView its crashing when settings the BackgroundColor. From what I saw in the Apple Documentation they have now the BackgroundConfiguration. 

I tried some fix for this that looks like working:

```
var version = UIDevice.CurrentDevice.SystemVersion;
var targetVersion = Convert.ToDouble(version);
			
if (targetVersion >= 140)
{
    var backConfig = header.BackgroundConfiguration;
    backConfig.BackgroundColor = UIColor.SystemGrayColor;
    header.BackgroundConfiguration = backConfig;
}
else
{
    if (header.BackgroundView != null)
        header.BackgroundView.BackgroundColor = _picker.PickerBackgroundColor;
}
```

Maybe you can take something from this to perpare a fix for later :)

**Comment by kolinkor** [comment]
Confirm. I have the same issue

**Comment by maksym-husiev** [comment]
The same on release version of iOS 14. Really need this to be fixed as soon as possible

**Comment by csamzhou** [comment]
#78 has been merged, waiting for the new release. :)

**Comment by roycornelissen** [comment]
@csamzhou @maksym-husiev @kolinkor Release 2.5.0 is now available in Nuget.

Let me know if this fixes your problems. Thanks for reporting and helping with the fixes!

**Comment by maksym-husiev** [comment]
@roycornelissen 2.5.0 working fine for me. Thx!

**Comment by roycornelissen** [comment]
phew, happy about that :)

**Comment by roycornelissen** [comment]
@MarcelWinkelEBF Hi, if you're OK with the fix, let me know, then I'll close this issue.

**Comment by MarcelWinkelEBF** [comment]
@roycornelissen Hi, thanks for the update. The crash is not appearing anymore. But I'm wondering, since CheckSystemVersion(14, 0) is used doesn't it mean with 14.1, 14.2 etc the crash will appear again? Isn't the check only for exactly 14.0 version?

**Comment by csamzhou** [comment]
@MarcelWinkelEBF Please refer to the documentation: [https://docs.microsoft.com/en-us/dotnet/api/uikit.uidevice.checksystemversion?view=xamarin-ios-sdk-12](url). CheckSystemVersion means: Whether the system version is greater than or equal to the specified major and minor values.

**Comment by MarcelWinkelEBF** [comment]
> @MarcelWinkelEBF Please refer to the documentation: [https://docs.microsoft.com/en-us/dotnet/api/uikit.uidevice.checksystemversion?view=xamarin-ios-sdk-12](url). CheckSystemVersion means: Whether the system version is greater than or equal to the specified major and minor values.

Thanks for the quick reply. My bad, sorry. Thanks for the fix.
