### ISSUE TITLE
App crash when use custom fonts + X.F. 4.8 + GMImagePicker 2.5.0 + iOS 14.1

### ISSUE THREAD

**Issue by luisabreu84** [roycornelissen/GMImagePicker.Xamarin#80]
Using custom fonts in the latest version, cause app crash.

**Custom fonts use:** 
picker.PickerBoldFontName = "OpenSans-Bold";
picker.PickerFontName = "OpenSans-Regular";
picker.UseCustomFontForNavigationBar = true;

**Version Info:**
iOS: 14.1 (Simulators and physical device)
Xamarin.Forms: 4.8.0.1364
GMImagePicker.Xamarin 2.5.0

**Note:**
This behavior working in early versions.

**Comment by danieltchaves** [comment]
Same problem

**Comment by Jucinei** [comment]
same problem

**Comment by roycornelissen** [comment]
Regarding iOS 14, please see the discussion I started in #86 .

**Comment by roycornelissen** [comment]
This is a regression introduced by me in https://github.com/roycornelissen/GMImagePicker.Xamarin/commit/dcacab0e786c455caa7eaba581b42e59334e7653. Using a custom font triggers endless recursion. Apologies for that. A fix is on the way.
