### ISSUE TITLE
Selection mark is not visible

### ISSUE THREAD

**Issue by martin-steglich** [roycornelissen/GMImagePicker.Xamarin#90]
Hi,  Checkmark images are not visible on selected items.

![Simulator Screen Shot - iPhone 8 - 2021-02-03 at 18 13 47](https://user-images.githubusercontent.com/8479907/106810364-9b5bd800-664b-11eb-8b36-f7f9dccf391a.png)

I saw the #65 issue but I couldn't resolve the problem.

I'm creating the picker this way:

`var picker = new GMImagePickerController
  {
      Title = "Select Photo",
      CustomDoneButtonTitle = "Finished",
      CustomCancelButtonTitle = "Cancel",
      ColsInPortrait = 4,
      ColsInLandscape = 7,
     
      DisplaySelectionInfoToolbar = true,
      AllowsMultipleSelection = true,
      ShowCameraButton = false,
      AutoSelectCameraImages = true,
      
      ModalPresentationStyle = UIModalPresentationStyle.FullScreen,
      MediaTypes = new[] { PHAssetMediaType.Image },
     
  }; `

Thank you!

**Comment by ratamahatta88** [comment]
Bumping this issue, reproducible on 2.5.1

**Comment by ratamahatta88** [comment]
Bumping this, can reproduce in the latest version, but not in 2.5.0

**Comment by martin-steglich** [comment]
I had to downgrade to version 2.5.0 to fix this bug.
